CREATE TABLE orders
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  users_id INTEGER REFERENCES users (id),
  purchase_time TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP,
  unit_cost DECIMAL NOT NULL,
  quantity INTEGER NOT NULL
);

CREATE TABLE events
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 4, INCREMENT BY 1),
  event_datetime TIMESTAMP NOT NULL UNIQUE,
  completed BOOLEAN NOT NULL
);

CREATE TABLE events_participants
(
  events_id INTEGER NOT NULL,
  users_id INTEGER NOT NULL,
  PRIMARY KEY (events_id, users_id),
  CONSTRAINT fk_events_participants_events_id_users_id FOREIGN KEY (events_id) REFERENCES events (id),
  CONSTRAINT fk_events_participants_users_id_users_id FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE event_info
(
  events_id INTEGER NOT NULL,
  distance DECIMAL DEFAULT NULL ,
  CONSTRAINT fk_event_info_events_id_events_id FOREIGN KEY (events_id) REFERENCES events (id)
);
