SET SCHEMA APP;

CREATE TABLE users
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 4, INCREMENT BY 1),
  username VARCHAR(128) UNIQUE NOT NULL,
  first_name VARCHAR(32),
  last_name VARCHAR(64),
  password VARCHAR(64) NOT NULL,
  enabled BOOLEAN DEFAULT true NOT NULL,
  last_login TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE groups
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 3, INCREMENT BY 1),
  group_name VARCHAR(50) NOT NULL
);

CREATE TABLE group_members
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 5, INCREMENT BY 1),
  username VARCHAR(128),
  group_id INTEGER,
  CONSTRAINT fk_group_members_users_username FOREIGN KEY (username) REFERENCES users (username),
  CONSTRAINT fk_group_members_groups_id FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE group_authorities
(
  group_id  INTEGER     NOT NULL,
  authority VARCHAR(50) NOT NULL,
  CONSTRAINT fk_group_authorities_groups_id FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE purchases
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  users_id INTEGER REFERENCES users (id),
  purchase_time TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP,
  quantity INTEGER
);

CREATE TABLE events
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 3, INCREMENT BY 1),
  event_datetime TIMESTAMP NOT NULL UNIQUE,
  completed BOOLEAN NOT NULL
);

CREATE TABLE events_participants
(
  events_id INTEGER NOT NULL,
  users_id INTEGER NOT NULL,
  PRIMARY KEY (events_id, users_id),
  CONSTRAINT fk_events_participants_events_id_users_id FOREIGN KEY (events_id) REFERENCES events (id),
  CONSTRAINT fk_events_participants_users_id_users_id FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE event_info
(
  events_id INTEGER NOT NULL,
  distance DOUBLE DEFAULT NULL ,
  CONSTRAINT fk_event_info_events_id_events_id FOREIGN KEY (events_id) REFERENCES events (id)
);