CREATE TABLE users
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 4, INCREMENT BY 1),
  username VARCHAR(128) UNIQUE NOT NULL,
  password VARCHAR(64) NOT NULL,
  enabled BOOLEAN DEFAULT true NOT NULL,
  last_login TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE user_details
(
  users_id INTEGER           NOT NULL
    CONSTRAINT user_details_pkey
    PRIMARY KEY
    CONSTRAINT user_details_users_id_fk
    REFERENCES users(id),
  balance  DECIMAL DEFAULT 0 NOT NULL,
  first_name VARCHAR(32) NOT NULL,
  last_name VARCHAR(64) NOT NULL
);

CREATE TABLE groups
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 3, INCREMENT BY 1),
  group_name VARCHAR(50) NOT NULL
);

CREATE TABLE group_members
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 5, INCREMENT BY 1),
  username VARCHAR(128),
  group_id INTEGER,
  CONSTRAINT fk_group_members_users_username FOREIGN KEY (username) REFERENCES users (username),
  CONSTRAINT fk_group_members_groups_id FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE group_authorities
(
  group_id  INTEGER     NOT NULL,
  authority VARCHAR(50) NOT NULL,
  CONSTRAINT fk_group_authorities_groups_id FOREIGN KEY (group_id) REFERENCES groups (id)
);
